name: Update visual regression expected screenshots

on:
  issue_comment:
    types: [created, edited]

defaults:
  run:
    shell: bash -l {0}

permissions: {}

jobs:
  update-expected-screenshots:
    name: Update screenshots
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'please update snapshots')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: jupyterlab/maintainer-tools/.github/actions/update-snapshots-checkout@f5d710df1483f19b666dd96aeabbe949a53642c2  # v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@f5d710df1483f19b666dd96aeabbe949a53642c2  # v1

      - name: Install
        run: pip install jupyterlab==4 .

      - name: Install dependencies
        shell: bash -l {0}
        working-directory: ui-tests
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        run: |
          jlpm install
          jlpm playwright install

      - uses: jupyterlab/maintainer-tools/.github/actions/update-snapshots@f5d710df1483f19b666dd96aeabbe949a53642c2  # v1
        with:
          npm_client: jlpm
          browser: chromium
          github_token: ${{ secrets.GITHUB_TOKEN }}
          start_server_script: 'null'
          test_folder: ui-tests
